name: cGamer
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.7.0+43

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.3.2+2
  flutter_launcher_icons: ^0.9.2
  splashscreen: ^1.2.0
  flutter_masked_text: ^0.8.0
  flutter_swiper: ^1.1.6
  http: ^0.13.3
  intl: ^0.17.0
  # package_info: ^0.4.3
  package_info_plus:
  flutter_flavor: ^1.1.2
  flutter_svg: ^1.0.3
  get:
  dart_notification_center: 
  get_storage:
  modal_progress_hud: ^0.1.3
  url_launcher: ^6.0.18
  flutter_secure_storage: ^3.3.4
  shimmer: ^1.1.2
  flutter_statusbarcolor: ^0.2.3
  percent_indicator: "^2.1.7+2"
  share: ^0.6.5+4
  #camera: ^0.8.1+3
  camera: ^0.9.4+3
  path: ^1.8.0
  local_auth: ^1.1.7
  clipboard: ^0.1.2+8
  open_file: ^3.0.3
  screenshot: ^1.2.3
  #esys_flutter_share: ^1.0.2
  regexpattern: ^1.0.0
  qr_mobile_vision: ^3.0.1 
  #qr_mobile_vision:
   # git:
    #  url: https://github.com/itsJoKr/flutter_qr_mobile_vision
     # ref: f72027aec9c147570f7126ac9e1e4265f0bdbf3b
  image_picker: ^0.8.4+1
  permission_handler: ^8.2.5
  carousel_slider: ^2.3.1
  lottie: ^1.2.1
  #flutter_credit_card_detector: 2.0.0
  flutter_native_image: ^0.0.5+3
  #zendesk:
  #   git:
  #    url: https://github.com/faelzanin/flutter-zendesk
  
#  zendesk2: ^2.0.0+1

  auto_size_text: ^2.1.0
  scrollable_positioned_list: ^0.1.10
  cached_network_image: ^3.1.0
  onesignal_flutter: ^3.2.3
  # camera_camera: ^1.0.34
  image_native_resizer: ^0.1.2
  google_ml_kit: ^0.7.2   
  flutter_ayetstudios:
    git: 
      url: https://github.com/faelzanin/flutter_ayetstudios
  google_mobile_ads: ^0.13.4
  tab_indicator_styler: ^2.0.0
  flutter_firebase_chat_core: ^1.4.2
  firebase_auth: ^3.1.1
  firebase_core_platform_interface: ^4.0.1
  plugin_platform_interface: ^2.0.0
  firebase_auth_web: ^3.1.0
  file_picker: ^4.1.3
  flutter_chat_ui: ^1.4.4
  firebase_storage: ^10.0.5
  firebase_core: ^1.7.0
  freshchat_sdk: ^0.9.5
  #irebase_messaging: ^10.0.8
  firebase_messaging:
    git:
      url: git://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging
  flutter_countdown_timer: ^4.1.0
  get_it: ^7.2.0
  flutter_fortune_wheel: ^1.1.0
  flutter_switch: ^0.3.2
  xml2json: ^5.3.1
  in_app_purchase: ^1.0.9
  geolocator: ^7.7.1
  uni_links: ^0.5.1
  external_app_launcher: ^2.0.2
  flutter_youtube_view: ^2.0.2

dependency_overrides:
  url_launcher_web: 2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker:
  mockito:   
  


#Change Icons
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/iconBackground.png"
  adaptive_icon_foreground: "assets/launcher/iconBackground.png"



flutter:


  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/home_images/
    - assets/images/tab_bar_icons/
    - assets/images/onboard_images/
    - assets/images/docs_images/
    - assets/images/logo/
    - assets/images/tab_bar_icons/
    - assets/images/profile_images/
    - assets/images/deposit_way_icons/
    - assets/images/complete_data_icons/
    - assets/images/profile_images/my_progress_images/
    - assets/images/marketplace/
    - assets/images/wallet_images/
    - assets/images/account_activation_icons/
    - assets/images/gamification_icons/
    - assets/images/play_to_win_games_images/
    - assets/images/cla_images/
    - assets/images/play_together/
  

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

