import 'package:cGamer/app/binding/coin_wallet_bindings/success_buy_coin_binding.dart';
import 'package:cGamer/app/binding/coin_wallet_bindings/transfer_coin_binding.dart';
import 'package:cGamer/app/binding/score_bindings/cashback_bindings/cashback_binding.dart';
import 'package:cGamer/app/binding/score_bindings/payment_score_bindings/payment_score_binding.dart';
import 'package:cGamer/app/ui/components/score_components/score_sub_pages/score_ranking.dart';
import 'package:cGamer/app/ui/pages/account_activation/account_activation_page.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/buy_coin_view.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/coin_transfer_password_view.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/coin_transfer_review.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/coin_transfer_success.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/coin_wallet.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/coin_withdraw_review.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/coin_withdraw_view.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/confirm_buy_coin.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/mafa_extract_page.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/success_buy_coin.dart';
import 'package:cGamer/app/ui/pages/coin_wallet/transfer_coin_view.dart';
import 'package:get/get.dart';
import 'package:cGamer/app/routes/routes_export.dart';
import 'package:cGamer/app/ui/pages/pages.dart';
import '../binding/bindings.dart';

class AppPages {
  static final routes = [
    GetPage(
      name: Routes.SPLASHSCREEEN,
      page: () => SplashScreenPage(),
    ),
    GetPage(
      name: Routes.ONBOARD,
      binding: OnBoardBinding(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => OnBoardPage(),
    ),
    GetPage(
      name: Routes.LOGIN,
      // transition: Transition.cupertino,
      // transitionDuration: Duration(milliseconds: 700),
      binding: LoginBinding(),
      page: () => LoginPage(),
    ),
    GetPage(
      name: Routes.SINGUP_EMAIL_STEP,
      transition: Transition.cupertino,
      binding: SignUpEmailStepBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => EmailStepPage(),
    ),
    GetPage(
      name: Routes.SINGUP_MOTHER_NAME_STEP,
      transition: Transition.cupertino,
      binding: MotherNameBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => MotherNameStepView(),
    ),
    GetPage(
      name: Routes.SINGUP_NAME_CPF_STEP,
      transition: Transition.cupertino,
      binding: NameCpfStepBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => NameCpfStepPage(),
    ),
    GetPage(
      name: Routes.SINGUP_NAME_PREFERRENCES_STEP,
      transition: Transition.cupertino,
      binding: NamePreferrencesBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => NamePreferrencesPage(),
    ),
    GetPage(
      name: Routes.SINGUP_BIRTH_MNAME_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: BirthBinding(),
      page: () => BirthPage(),
    ),
    GetPage(
      name: Routes.SINGUP_PASSWORD_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PasswordBinding(),
      page: () => PasswordStep(),
    ),
    GetPage(
      name: Routes.RETRIVE_PASSWORD,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: RetrivePasswordEmailBinding(),
      page: () => RetrivePasswordPage(),
    ),
    GetPage(
      name: Routes.RETRIVE_PASSWORD_EMAIL_CODE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: RetrivePasswordCodeBinding(),
      page: () => EmailCodePage(),
    ),
    GetPage(
      name: Routes.SUCCESS_RETRIVE_PASSWORD,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => SuccesRecoveredPage(),
    ),
    GetPage(
      name: Routes.SINGUP_CEP_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: CepBinding(),
      page: () => CepStepPage(),
    ),
    GetPage(
      name: Routes.SINGUP_ADRESS_COMPLEMENT_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: AdressComplementBinding(),
      page: () => AdressComplementPage(),
    ),
    GetPage(
      name: Routes.SINGUP_ADRESS_UF_CITY,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: UfCityBinding(),
      page: () => UfCityStepPage(),
    ),
    GetPage(
      name: Routes.SUCCESS_COMPLETE_REGISTER,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => SuccessCompleteRegister(),
    ),
    GetPage(
      name: Routes.SUCCESS_ACCOUNT_CREATED,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => AccountCreatedSuccess(),
    ),
    GetPage(
      name: Routes.SINGUP_PHONE_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PhoneStepBinding(),
      page: () => PhoneStepView(),
    ),
    GetPage(
      name: Routes.SINGUP_PHONE_CODE_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PhoneCodeBinding(),
      page: () => PhoneCodeStepView(),
    ),
    GetPage(
      name: Routes.PROFILE,
      transition: Transition.downToUp,
      transitionDuration: Duration(milliseconds: 700),
      binding: ProfileBinding(),
      page: () => ProfileView(),
    ),
    GetPage(
      name: Routes.MAIN_PAGES_HOLDER,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PagesHolderBinding(),
      page: () => MainPagesHolder(),
    ),
    GetPage(
        name: Routes.MY_PROGRESS,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: MyProgressBinding(),
        page: () => MyProgressPage()),
    GetPage(
      name: Routes.VALIDATE_DOCS_CHOSSE_TYPE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ChooseDoctypeBinding(),
      page: () => ChooseDocTypeView(),
    ),
    GetPage(
      name: Routes.VALIDATE_DOCS_TIPS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: TakePhotoTipsBinding(),
      page: () => TakePhotoTipsView(),
    ),
    GetPage(
      name: Routes.VALIDATE_DOCS_SELFIE_TIPS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: SelfieBinding(),
      page: () => SelfieView(),
    ),
    GetPage(
      name: Routes.VALIDATE_DOCS_SENDED,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => SuccessValidateView(),
    ),
    GetPage(
      name: Routes.CHOOSE_DEPOSIT_WAY,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: CashInTypeBinding(),
      page: () => CashInTypesView(),
    ),
    GetPage(
      name: Routes.CHOOSE_DEPOSIT_VALUE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: DepositValueBinding(),
      page: () => DepositValueView(),
    ),
    GetPage(
      name: Routes.TICKET_VIEW,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: TicketBinding(),
      page: () => TicketView(),
    ),
    GetPage(
      name: Routes.CHANGE_PASSWORD,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: OldPasswordStepBinding(),
      page: () => ChangePasswordView(),
    ),
    GetPage(
      name: Routes.SECURITY,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: SecurityBinding(),
      page: () => SecurityView(),
    ),
    GetPage(
      name: Routes.TICKET_LIST_VIEW,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: TicketListBinding(),
      page: () => TicketsListView(),
    ),
    GetPage(
        name: Routes.DEPOSIT_TED,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: CashInTedBinding(),
        page: () => CashInTedView()),
    GetPage(
        name: Routes.ACCOUNT_DATA_LIST,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: AccountDataListBinding(),
        page: () => AccountDataListView()),
    GetPage(
        name: Routes.PERSONAL_DATA,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: PersonalDataBinding(),
        page: () => PersonalDataView()),
    GetPage(
        name: Routes.PHONE_DATA,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: PhoneDataBinding(),
        page: () => PhoneDataView()),
    GetPage(
        name: Routes.ADDRESS_DATA,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: AddressDataBinding(),
        page: () => AddressDataView()),
    GetPage(
      name: Routes.TRANSFER_CHOOSE_PEOPLE,
      transition: Transition.cupertino,
      bindings: [
        ChooseContactBinding(),
      ],
      transitionDuration: Duration(milliseconds: 700),
      page: () => ChooseContactTransfer(),
    ),
    GetPage(
      name: Routes.TRANSFER_CONFIRM,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => ConfirmValue(),
    ),
    GetPage(
      name: Routes.TRANSFER_CONFIRM_PASSWORD,
      transition: Transition.cupertino,
      binding: TransferPasswordBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => PasswordConfirm(),
    ),
    GetPage(
      name: Routes.TRANSFER_SUCCESS,
      transition: Transition.cupertino,
      binding: SuccessTransferBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => SuccessTransfer(),
    ),
    GetPage(
      name: Routes.TRANSFER_CPF,
      transition: Transition.cupertino,
      binding: CpfToTransferBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => CpfTotransfer(),
    ),
    GetPage(
      name: Routes.TRANSFER_AT,
      transition: Transition.cupertino,
      binding: AtToTransferBinding(),
      transitionDuration: Duration(milliseconds: 700),
      page: () => AtToTransfer(),
    ),
    GetPage(
      name: Routes.FAQ_CATEGORY,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: FAQCategoryBinding(),
      page: () => FAQCategoryView(),
    ),
    GetPage(
      name: Routes.FAQ_QUESTIONS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: FAQQuestionsBinding(),
      page: () => FAQQuestionsView(),
    ),
    GetPage(
        name: Routes.FAQ_ANSWER,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: FAQAnswerBinding(),
        page: () => FAQAnswerView()),
    GetPage(
      name: Routes.TRANSFER_RECEIPT,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ReceiptBinding(),
      page: () => ReceiptPage(),
    ),
    GetPage(
      name: Routes.INVITE_FRIEND,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: InviteFriendBinding(),
      page: () => InviteFriendView(),
    ),
    GetPage(
      name: Routes.SIGNUP_USERNAME,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: UsernameBinding(),
      page: () => UsernameStepView(),
    ),
    GetPage(
      name: Routes.TRANSFER_TED_CPF_CNPJ,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: TedExternBinding(),
      page: () => TedExternCpfCnpjView(),
    ),
    GetPage(
      name: Routes.TRANSFER_TED_CHOOSE_BANK,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ChooseBankBinding(),
      page: () => ChooseBankView(),
    ),
    GetPage(
      name: Routes.TRANSFER_TED_CHOOSE_ACCOUNT_TYPE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => TedChooseAccountType(),
    ),
    GetPage(
      name: Routes.TRANSFER_TED_ACCOUNT_INFO,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: TedAccountInfoBinding(),
      page: () => TedAccountInfo(),
    ),
    GetPage(
      name: Routes.TRANSFER_TED_CONFIRM,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => TedConfirmView(),
    ),
    GetPage(
      name: Routes.RECHARGE_PHONE_NUMBER,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: RechargeNumberBinding(),
      page: () => RechargeNumberView(),
    ),
    GetPage(
      name: Routes.RECHARGE_PHONE_PROVIDERS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PhoneProvidersBinding(),
      page: () => PhoneProvidersView(),
    ),
    GetPage(
      name: Routes.RECHARGE_PHONE_VALUES,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PhoneRechargeValuesBinding(),
      page: () => PhoneRechargeValuesView(),
    ),
    GetPage(
      name: Routes.RECHARGE_PHONE_CONFIRM,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PhoneRechargeConfirmBinding(),
      page: () => PhoneRechargeConfirmView(),
    ),
    GetPage(
      name: Routes.RECHARGE_PHONE_PASSWORD,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PhoneRechargePasswordBinding(),
      page: () => PhoneRechargePasswordView(),
    ),
    GetPage(
      name: Routes.RECHARGE_PHONE_SUCCESS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: PhoneRechargeSuccessBinding(),
      page: () => PhoneRechargeSuccessView(),
    ),
    GetPage(
      name: Routes.PAYMENT_READ_BAR_CODE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ReadBarCodeBinding(),
      page: () => ReadBarCodePage(),
    ),
    GetPage(
      name: Routes.PAYMENT_WRITE_BAR_CODE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: WriteBarCodeBinding(),
      page: () => WritebarCodePage(),
    ),
    GetPage(
      name: Routes.TRANSFER_TED_EXTERN_PASSWORD,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ExternPasswordBinding(),
      page: () => PasswordTransferExtern(),
    ),
    GetPage(
        name: Routes.TRANSFER_TED_EXTERN_SUCCESS,
        transition: Transition.cupertino,
        transitionDuration: Duration(milliseconds: 700),
        binding: TedExternSuccessBinding(),
        page: () => SuccessTransferExtern()),
    GetPage(
      name: Routes.PAYMENT_BILL_CONFIRM,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ConfirmBillPaymentBinding(),
      page: () => ConfirmBillPaymentPage(),
    ),
    GetPage(
      name: Routes.PAYMENT_BILL_SUCCESS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: BillPaymentSuccessBinding(),
      page: () => BillPaymentSuccessPage(),
    ),
    GetPage(
      name: Routes.PAYMENT_BILL_PASSWORD,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: BillPaymentPasswordBinding(),
      page: () => BillPaymentPasswordPage(),
    ),
    GetPage(
      name: Routes.PAYMENT_BILL_RECEIPT,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ReceiptBinding(),
      page: () => BillPaymentReceiptPage(),
    ),
    GetPage(
      name: Routes.MARKETPLACE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: MarketplaceBinding(),
      page: () => MarketplaceView(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_CATEGORY_ITEMS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: CategoryBinding(),
      page: () => MarketplaceCategoryItemsView(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_SUBCATEGORY_ITEMS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: SubCategoryBinding(),
      page: () => MarketplaceSubCategoryItemsView(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_STORE_PARTNER_DETAILS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: StorePartnerDetailBinding(),
      page: () => StorePartnerDetail(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_CONFIRM_BUY,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ProductDetailBinding(),
      page: () => MarketplaceConfirmBuy(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_CONFIRM_TERMS_USE,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: TermsUseBinding(),
      page: () => TermsUseView(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_PASSSWORD_CONFIRM,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: MarketPlacePasswordBinding(),
      page: () => MarketPlacePasswordView(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_PURCHASE_SUCCESS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: MarketPlaceSuccessBinding(),
      page: () => MarketPlaceSuccessPurchase(),
    ),
    GetPage(
      name: Routes.MARKETPLACE_CATEGORY_GAMES,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: CategoryGamesBinding(),
      page: () => MarketplaceCategoryGamesView(),
    ),
    GetPage(
      name: Routes.WALLET_CARDS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: CardOverviewBinding(),
      page: () => WalletCardsView(),
    ),
    GetPage(
        binding: CardExtractBinding(),
        name: Routes.WALLET_EXTRACT_CARD,
        page: () => CardExtractPage()),
    GetPage(
      name: Routes.WALLET_ADD_VIRTUAL_CARD_ALIAS_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: VirtualCardAliasStepBinding(),
      page: () => AddCardAliasStep(),
    ),
    GetPage(
      name: Routes.WALLET_ADD_VIRTUAL_CARD_NAME_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: VirtualCardNameStepBinding(),
      page: () => AddCardNameStep(),
    ),
    GetPage(
      name: Routes.WALLET_ADD_VIRTUAL_CARD_PASSWORD_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: VirtualCardCreatePasswordStepBinding(),
      page: () => AddCardPasswordStep(),
    ),
    GetPage(
      name: Routes.WALLET_ADD_VIRTUAL_CARD_ACCOUNT_PASSWORD_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: VirtualCardAccountPasswordStepBinding(),
      page: () => AddCardAccountPasswordStep(),
    ),
    GetPage(
      name: Routes.WALLET_ADD_CARD_IN_PROCCESS_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      // binding: CategoryGamesBinding(),
      page: () => AddCardInProccessStep(),
    ),
    GetPage(
      name: Routes.WALLET_BLOCK_VIRTUAL_CARD_ACCOUNT_PASSWORD_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: BlockVirtualCardAccountPasswordBinding(),
      page: () => VirtualCardBlockAccountPasswordStep(),
    ),
    GetPage(
      name: Routes.WALLET_BLOCK_VIRTUAL_CARD_PASSWORD_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: BlockVirtualCardPasswordBinding(),
      page: () => VirtualCardBlockPasswordStep(),
    ),
    GetPage(
      name: Routes.WALLET_BLOCK_VIRTUAL_CARD_SUCCESS_STEP,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: BlockVirtualCardSuccessBinding(),
      page: () => VirtualCardBlockSuccessStep(),
    ),
    GetPage(
      name: Routes.WALLET_CARD_INFO,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: CardInfoBinding(),
      page: () => CardInfo(),
    ),
    // GetPage(
    //   name: Routes.WALLET_EXTERN_CARD_FIRST_INFO,
    //   transition: Transition.cupertino,
    //   transitionDuration: Duration(milliseconds: 700),
    //   binding: ExternCardFirstStepBinding(),
    //   page: () => AddExternCardFirstStep(),
    // ),
    GetPage(
      name: Routes.WALLET_EXTERN_CARD_SECOND_INFO,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: CardSecondStepBinding(),
      page: () => AddExternCardSecondStep(),
    ),
    GetPage(
      name: Routes.WALLET_ADD_EXTERN_CARD_SUCCESS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => CardAddedSuccess(),
    ),
    GetPage(
      name: Routes.WALLET_SETTINGS_OPTIONS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: SettingsOptionsBinding(),
      page: () => SettingsOptionsPage(),
    ),
    GetPage(
      name: Routes.WALLET_SETTINGS_PASSWORD_ACTUAL,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: VirtualCardPasswordBinding(),
      page: () => SettingsActualPage(),
    ),
    GetPage(
      name: Routes.WALLET_SETTINGS_PASSWORD_NEW,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      binding: ChangePasswordVirtualCardBinding(),
      page: () => SettingsNewPage(),
    ),
    GetPage(
      name: Routes.WALLET_SETTINGS_PASSWORD_CHANGE_SUCCESS,
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
      page: () => SettingsPasswordChangeSuccess(),
    ),
    GetPage(
      name: Routes.EXTRACT_PAGE,
      transition: Transition.cupertino,
      // transitionDuration: Duration(milliseconds: 700),
      binding: ExtractBinding(),
      page: () => ExtractPage(),
    ),
    GetPage(
      name: Routes.CUSTOMIZATION,
      page: () => CustomizationView(),
      transition: Transition.cupertino,
      binding: CustomizationBinding(),
      transitionDuration: Duration(milliseconds: 700),
    ),
    GetPage(
      name: Routes.CUSTOMIZATION_CONFIRM_PURCHASE,
      page: () => ConfirmPurchase(),
      binding: ConfirmPurchaseBinding(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
    ),
    GetPage(
      name: Routes.CUSTOMIZATION_CONFIRM_PURCHASE_SUCESS,
      page: () => CustomizationSucessView(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
    ),
    GetPage(
      name: Routes.BUY_BADGES,
      page: () => BuyBadgeView(),
      binding: BuyBadgeBinding(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
    ),
    GetPage(
      name: Routes.BUY_BADGES_CONFIRM,
      page: () => BuyBadgePasswordView(),
      binding: BuyBadgePasswordBinding(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
    ),
    GetPage(
      name: Routes.BUY_BADGES_SUCCESS,
      page: () => BuyBadgeSuccessView(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
    ),
    GetPage(
      name: Routes.MY_BADGES,
      page: () => MyBadgeView(),
      binding: MyBadgeBinding(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
    ),
    // GetPage(
    //   name: Routes.ACCOUNT_ACTIVATION,
    //   page: () => AccountActivationPage(),
    //   transition: Transition.cupertino,
    //   transitionDuration: Duration(milliseconds: 700),
    // ),
    GetPage(
      name: Routes.PARTNERS_POINTS_LIST,
      page: () => PartnersPoints(),
      binding: PartnersPointsBinding(),
      transition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 700),
    ),
    GetPage(name: Routes.PARTNES_DETAILS, page: () => PartnerDetailsPage()),
    GetPage(
        name: Routes.CASHBACK,
        page: () => CashbackPage(),
        binding: CashbackBinding()),
    GetPage(name: Routes.BUY_GIFT_CARD, page: () => BuyGiftCardPage()),
    GetPage(
        name: Routes.PAYMENT_SCORE_PASSWORD,
        page: () => PaymentScorePassword(),
        binding: PaymentScoreBinding()),
    GetPage(name: Routes.TRADE_SUCESS, page: () => TradeSucessPage()),
    GetPage(
        name: Routes.RANKING_TOP50,
        page: () => ScoreRanking(),
        binding: RankingBinding()),
    GetPage(
        name: Routes.PLAY_TO_WIN,
        page: () => PlayToWinPage(),
        binding: PlayToWinBinding()),
    GetPage(
      name: Routes.LOL_CONNECTION,
      page: () => LolConnectionPage(),
    ),
    GetPage(
        name: Routes.LOL_VALIDATION,
        page: () => LolAccountValidation(),
        binding: LolVerificationBinding()),
    GetPage(
      name: Routes.LOL_SUCCESS,
      page: () => LoLConnectionSuccessView(),
    ),
    GetPage(
      name: Routes.CLAN,
      page: () => Clan(),
      binding: ClanBinding(),
    ),
    GetPage(
        name: Routes.CREATE_NEW_CLAN,
        page: () => CreateNewClan(),
        binding: CreateNewClanBinding()),
    GetPage(
      name: Routes.CLAN_DETAILS,
      page: () => ClanDetailsPage(),
      binding: ClanDetailsBinding(),
    ),
    GetPage(
      name: Routes.OTHER_CLAN,
      page: () => ClanDetailsOtherPage(),
      binding: ClanDetailOtherBinding(),
    ),

    GetPage(
      name: Routes.CLAN_INTERACTIONS,
      page: () => ClanInteractions(),
      binding: ClanIterationsBinding(),
    ),
    GetPage(
      name: Routes.CLAN_REQUEST_ENTRY,
      page: () => ClanRequestEntryList(),
      binding: ClanRequestEntryBinding(),
    ),
    GetPage(
      name: Routes.CLAN_MANAGE_MEMBERS,
      page: () => ManageMembersList(),
      binding: ClanManageMembersBinding(),
    ),
    GetPage(
      name: Routes.CLAN_RANKING,
      page: () => ClanRankingTabsPage(),
      binding: ClanRankingBinding(),
    ),
    GetPage(
      name: Routes.CLAN_ROULETTE,
      binding: ClanRouleteBinding(),
      page: () => RoulettePage(),
    ),
    GetPage(
        name: Routes.CLAN_TROPHY_HUNT,
        page: () => TrophyHunt(),
        binding: ClanTrophyHuntBinding()),
    GetPage(
        name: Routes.CLAN_JOGO_VELHA,
        page: () => JogoVelhaPage(),
        binding: JogoVelhaBinding()),
    GetPage(
      name: Routes.PLAY_TOGETHER,
      binding: PlayTogetherBinding(),
      page: () => PlayTogetherPage(),
    ),
    GetPage(
        name: Routes.ADD_NEW_GAME,
        page: () => AddNewGamePage(),
        binding: AddGameBinding()),
    GetPage(
        name: Routes.ADD_NEW_GAME_CONFIRMATION,
        page: () => AddNewGameConfirmationPage(),
        binding: AddGameConfirmationBinding()),
    GetPage(
        name: Routes.PLAYER_SEARCH,
        page: () => PlayerSearchPage(),
        binding: PlayerSearchBinding()),
    GetPage(
        name: Routes.FOUND_PLAYER,
        page: () => FoundPlayerPage(),
        binding: FoundSearchBinding()),
    GetPage(
        name: Routes.NEARBY_PLAYERS,
        page: () => NearbyPlayersPage(),
        binding: NearBySearchPlayersBinding()),
    GetPage(name: Routes.PRO, page: () => ProView(), binding: ProBinding()),
    GetPage(
        name: Routes.PRIME_AREA,
        page: () => PrimeArea(),
        binding: PrimeAreaBinding()),
    GetPage(
        name: Routes.EDIT_A_GAME,
        page: () => EditAGamePage(),
        binding: EditAGameBinding()),
    GetPage(
        name: Routes.CONNECTIONS,
        page: () => ConnectionsPage(),
        binding: ConnectionBinding()),
    GetPage(
        name: Routes.SEARCH_FRIENDS,
        page: () => SearchFriends(),
        binding: SearchFriendBinding()),
    GetPage(
        name: Routes.USER_PROFILE,
        page: () => UserProfilePage(),
        binding: UserProfileBinding()),
    GetPage(
        name: Routes.CLAN_QUIZ, page: () => QuizPage(), binding: QuizBinding()),
    GetPage(
        name: Routes.WALLET_BUY_COIN,
        page: () => BuyCoinView(),
        binding: BuyCoinBinding()),
    GetPage(
        name: Routes.WALLET_CONFIRM_BUY_COIN,
        page: () => ConfirmBuyCoin(),
        binding: ConfirmBuyCoinBinding()),
    GetPage(
        name: Routes.WALLET_SUCCESS_BUY_COIN,
        page: () => SuccessBuyCoin(),
        binding: SuccessBuyCoinBinding()),

    GetPage(
        name: Routes.WALLET_COIN_TRANSFER,
        page: () => TransferCoinPage(),
        binding: TransferCoinBinding()
        // binding: ConfirmBuyCoinBinding(),
        ),
    GetPage(
      name: Routes.MAFA_EXTRACT_PAGE,
      page: () => MafaExtractPage(),
      // binding: ConfirmBuyCoinBinding(),
    ),

    GetPage(
      name: Routes.WALLET_COIN_TRANSFER_REVIEW,
      page: () => TransferCoinReview(),
      // binding: ConfirmBuyCoinBinding(),
    ),
    GetPage(
      name: Routes.WALLET_COIN_PASSWORD,
      page: () => CoinTransferPasswordView(),
      // binding: ConfirmBuyCoinBinding(),
    ),

    GetPage(
      name: Routes.WALLET_COIN_TRANSFER_SUCCESS,
      page: () => CoinTransferSuccess(),
      // binding: ConfirmBuyCoinBinding(),
    ),

    GetPage(
      name: Routes.WALLET_COIN_WITHDRAW_VIEW,
      page: () => WithdrawCoinView(),
      binding: WithdrawCoinBinding(),
    ),

    GetPage(
      name: Routes.WALLET_COIN_WITHDRAW_CONFIRM,
      page: () => WithdrawCoinReview(),
      binding: WithdrawConfirmCoinBinding(),
    ),

    //GetPage(page: () => Pho toQualityView(), name: Routes.PHOTO_QUALITY_VIEW)
  ];
}
